---
- name: Setup the postgres repo for EL7
  yum_repository:
    name: "postgres-{{ pg_ver }}"
    description: "PostgreSQL {{ pg_ver }}"
    baseurl: "http://yum.postgresql.org/{{ pg_ver }}/redhat/rhel-{{ ansible_distribution_major_version }}-x86_64"
    gpgcheck: no
    enabled: yes
    state: present
  when: (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
