---
- include: add_postgres_repos.yaml

- name: Install Postgres related packages
  yum:
    name: "{{ item }}"
  with_items: "{{ packages_to_install }}"

- include: pg_init.yaml

- include: configure_pg.yaml

- name: Enable Postgres related services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ enabled_services }}"
