---
- include: add_postgres_repos.yml

- name: Install Postgres related packages
  yum:
    name: "{{ item }}"
  with_items: "{{ packages_to_install }}"

- include: pg_init.yml

- include: configure_pg.yml

- name: Enable Postgres related services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ enabled_services }}"
